/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BillingStatus = IDL.Variant({
  'active' : IDL.Null,
  'grace' : IDL.Null,
  'restricted' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const PaymentFailureLog = IDL.Record({
  'attempts' : IDL.Nat,
  'timestamp' : IDL.Nat,
  'amount' : IDL.Nat,
  'lastAttempt' : IDL.Nat,
  'reason' : IDL.Text,
});
export const BillingRecord = IDL.Record({
  'status' : BillingStatus,
  'businessId' : IDL.Text,
  'paymentFailureLogs' : IDL.Vec(PaymentFailureLog),
  'lastRestrictionTime' : IDL.Opt(IDL.Nat),
  'gracePeriodStart' : IDL.Opt(IDL.Nat),
  'nextRetryTime' : IDL.Opt(IDL.Nat),
  'retryAttempts' : IDL.Nat,
});
export const BusinessProfile = IDL.Record({
  'billingDetails' : IDL.Text,
  'size' : IDL.Text,
  'subscriptionTier' : IDL.Text,
  'businessName' : IDL.Text,
  'storageEstimateGb' : IDL.Nat,
  'contactEmail' : IDL.Text,
  'industry' : IDL.Text,
});
export const SupportStatus = IDL.Variant({
  'resolved' : IDL.Null,
  'closed' : IDL.Null,
  'open' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const SupportCategory = IDL.Variant({
  'technicalIssue' : IDL.Null,
  'accountAccess' : IDL.Null,
  'other' : IDL.Null,
  'security' : IDL.Null,
  'billing' : IDL.Null,
});
export const SupportRequest = IDL.Record({
  'id' : IDL.Text,
  'status' : SupportStatus,
  'organizationName' : IDL.Text,
  'fullName' : IDL.Text,
  'submittedAt' : IDL.Nat,
  'description' : IDL.Text,
  'businessEmail' : IDL.Text,
  'supportCategory' : SupportCategory,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const FileMetadata = IDL.Record({
  'id' : IDL.Text,
  'blob' : ExternalBlob,
  'name' : IDL.Text,
  'ownerBusinessId' : IDL.Text,
  'sizeBytes' : IDL.Nat,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkServiceAccess' : IDL.Func([IDL.Text], [BillingStatus], ['query']),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'deleteBusinessProfile' : IDL.Func([IDL.Text], [], []),
  'deleteFileMetadata' : IDL.Func([IDL.Text], [], []),
  'deleteSupportRequest' : IDL.Func([IDL.Text], [], []),
  'deleteThemePreference' : IDL.Func([], [], []),
  'getAllBillingRecords' : IDL.Func([], [IDL.Vec(BillingRecord)], ['query']),
  'getAllBusinessProfiles' : IDL.Func(
      [],
      [IDL.Vec(BusinessProfile)],
      ['query'],
    ),
  'getAllSupportRequests' : IDL.Func([], [IDL.Vec(SupportRequest)], ['query']),
  'getBillingRecordDetails' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(BillingRecord)],
      ['query'],
    ),
  'getBillingStatus' : IDL.Func([IDL.Text], [BillingStatus], ['query']),
  'getBusinessFiles' : IDL.Func([IDL.Text], [IDL.Vec(FileMetadata)], ['query']),
  'getBusinessProfile' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(BusinessProfile)],
      ['query'],
    ),
  'getCallerBusinessProfile' : IDL.Func(
      [],
      [IDL.Opt(BusinessProfile)],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCustomerBillingStatus' : IDL.Func([], [BillingStatus], ['query']),
  'getFileMetadata' : IDL.Func([IDL.Text], [IDL.Opt(FileMetadata)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getSupportRequest' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(SupportRequest)],
      ['query'],
    ),
  'getThemePreference' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'handleFailedPayment' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
      [],
      [],
    ),
  'handleSuccessfulPayment' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [], []),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isInGracePeriod' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'isServiceRestricted' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'manuallySetBillingStatus' : IDL.Func([IDL.Text, BillingStatus], [], []),
  'retryPaymentAttempt' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [], []),
  'saveBusinessFileMetadata' : IDL.Func([IDL.Text, FileMetadata], [], []),
  'saveCallerBusinessProfile' : IDL.Func([BusinessProfile], [], []),
  'saveThemePreference' : IDL.Func([IDL.Text], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'submitSupportRequest' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        SupportCategory,
        IDL.Text,
        IDL.Nat,
      ],
      [],
      [],
    ),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateSupportRequestStatus' : IDL.Func([IDL.Text, SupportStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BillingStatus = IDL.Variant({
    'active' : IDL.Null,
    'grace' : IDL.Null,
    'restricted' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const PaymentFailureLog = IDL.Record({
    'attempts' : IDL.Nat,
    'timestamp' : IDL.Nat,
    'amount' : IDL.Nat,
    'lastAttempt' : IDL.Nat,
    'reason' : IDL.Text,
  });
  const BillingRecord = IDL.Record({
    'status' : BillingStatus,
    'businessId' : IDL.Text,
    'paymentFailureLogs' : IDL.Vec(PaymentFailureLog),
    'lastRestrictionTime' : IDL.Opt(IDL.Nat),
    'gracePeriodStart' : IDL.Opt(IDL.Nat),
    'nextRetryTime' : IDL.Opt(IDL.Nat),
    'retryAttempts' : IDL.Nat,
  });
  const BusinessProfile = IDL.Record({
    'billingDetails' : IDL.Text,
    'size' : IDL.Text,
    'subscriptionTier' : IDL.Text,
    'businessName' : IDL.Text,
    'storageEstimateGb' : IDL.Nat,
    'contactEmail' : IDL.Text,
    'industry' : IDL.Text,
  });
  const SupportStatus = IDL.Variant({
    'resolved' : IDL.Null,
    'closed' : IDL.Null,
    'open' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const SupportCategory = IDL.Variant({
    'technicalIssue' : IDL.Null,
    'accountAccess' : IDL.Null,
    'other' : IDL.Null,
    'security' : IDL.Null,
    'billing' : IDL.Null,
  });
  const SupportRequest = IDL.Record({
    'id' : IDL.Text,
    'status' : SupportStatus,
    'organizationName' : IDL.Text,
    'fullName' : IDL.Text,
    'submittedAt' : IDL.Nat,
    'description' : IDL.Text,
    'businessEmail' : IDL.Text,
    'supportCategory' : SupportCategory,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const FileMetadata = IDL.Record({
    'id' : IDL.Text,
    'blob' : ExternalBlob,
    'name' : IDL.Text,
    'ownerBusinessId' : IDL.Text,
    'sizeBytes' : IDL.Nat,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkServiceAccess' : IDL.Func([IDL.Text], [BillingStatus], ['query']),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'deleteBusinessProfile' : IDL.Func([IDL.Text], [], []),
    'deleteFileMetadata' : IDL.Func([IDL.Text], [], []),
    'deleteSupportRequest' : IDL.Func([IDL.Text], [], []),
    'deleteThemePreference' : IDL.Func([], [], []),
    'getAllBillingRecords' : IDL.Func([], [IDL.Vec(BillingRecord)], ['query']),
    'getAllBusinessProfiles' : IDL.Func(
        [],
        [IDL.Vec(BusinessProfile)],
        ['query'],
      ),
    'getAllSupportRequests' : IDL.Func(
        [],
        [IDL.Vec(SupportRequest)],
        ['query'],
      ),
    'getBillingRecordDetails' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(BillingRecord)],
        ['query'],
      ),
    'getBillingStatus' : IDL.Func([IDL.Text], [BillingStatus], ['query']),
    'getBusinessFiles' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(FileMetadata)],
        ['query'],
      ),
    'getBusinessProfile' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(BusinessProfile)],
        ['query'],
      ),
    'getCallerBusinessProfile' : IDL.Func(
        [],
        [IDL.Opt(BusinessProfile)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCustomerBillingStatus' : IDL.Func([], [BillingStatus], ['query']),
    'getFileMetadata' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(FileMetadata)],
        ['query'],
      ),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getSupportRequest' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(SupportRequest)],
        ['query'],
      ),
    'getThemePreference' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'handleFailedPayment' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
    'handleSuccessfulPayment' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [], []),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isInGracePeriod' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'isServiceRestricted' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'manuallySetBillingStatus' : IDL.Func([IDL.Text, BillingStatus], [], []),
    'retryPaymentAttempt' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [], []),
    'saveBusinessFileMetadata' : IDL.Func([IDL.Text, FileMetadata], [], []),
    'saveCallerBusinessProfile' : IDL.Func([BusinessProfile], [], []),
    'saveThemePreference' : IDL.Func([IDL.Text], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'submitSupportRequest' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          SupportCategory,
          IDL.Text,
          IDL.Nat,
        ],
        [],
        [],
      ),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateSupportRequestStatus' : IDL.Func([IDL.Text, SupportStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };