/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BillingRecord {
  'status' : BillingStatus,
  'businessId' : string,
  'paymentFailureLogs' : Array<PaymentFailureLog>,
  'lastRestrictionTime' : [] | [bigint],
  'gracePeriodStart' : [] | [bigint],
  'nextRetryTime' : [] | [bigint],
  'retryAttempts' : bigint,
}
export type BillingStatus = { 'active' : null } |
  { 'grace' : null } |
  { 'restricted' : null };
export interface BusinessProfile {
  'billingDetails' : string,
  'size' : string,
  'subscriptionTier' : string,
  'businessName' : string,
  'storageEstimateGb' : bigint,
  'contactEmail' : string,
  'industry' : string,
}
export type ExternalBlob = Uint8Array;
export interface FileMetadata {
  'id' : string,
  'blob' : ExternalBlob,
  'name' : string,
  'ownerBusinessId' : string,
  'sizeBytes' : bigint,
}
export interface PaymentFailureLog {
  'attempts' : bigint,
  'timestamp' : bigint,
  'amount' : bigint,
  'lastAttempt' : bigint,
  'reason' : string,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type SupportCategory = { 'technicalIssue' : null } |
  { 'accountAccess' : null } |
  { 'other' : null } |
  { 'security' : null } |
  { 'billing' : null };
export interface SupportRequest {
  'id' : string,
  'status' : SupportStatus,
  'organizationName' : string,
  'fullName' : string,
  'submittedAt' : bigint,
  'description' : string,
  'businessEmail' : string,
  'supportCategory' : SupportCategory,
}
export type SupportStatus = { 'resolved' : null } |
  { 'closed' : null } |
  { 'open' : null } |
  { 'inProgress' : null };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkServiceAccess' : ActorMethod<[string], BillingStatus>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'deleteBusinessProfile' : ActorMethod<[string], undefined>,
  'deleteFileMetadata' : ActorMethod<[string], undefined>,
  'deleteSupportRequest' : ActorMethod<[string], undefined>,
  'deleteThemePreference' : ActorMethod<[], undefined>,
  'getAllBillingRecords' : ActorMethod<[], Array<BillingRecord>>,
  'getAllBusinessProfiles' : ActorMethod<[], Array<BusinessProfile>>,
  'getAllSupportRequests' : ActorMethod<[], Array<SupportRequest>>,
  'getBillingRecordDetails' : ActorMethod<[string], [] | [BillingRecord]>,
  'getBillingStatus' : ActorMethod<[string], BillingStatus>,
  'getBusinessFiles' : ActorMethod<[string], Array<FileMetadata>>,
  'getBusinessProfile' : ActorMethod<[string], [] | [BusinessProfile]>,
  'getCallerBusinessProfile' : ActorMethod<[], [] | [BusinessProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCustomerBillingStatus' : ActorMethod<[], BillingStatus>,
  'getFileMetadata' : ActorMethod<[string], [] | [FileMetadata]>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getSupportRequest' : ActorMethod<[string], [] | [SupportRequest]>,
  'getThemePreference' : ActorMethod<[], [] | [string]>,
  'handleFailedPayment' : ActorMethod<
    [string, string, bigint, bigint],
    undefined
  >,
  'handleSuccessfulPayment' : ActorMethod<[string, bigint, bigint], undefined>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isInGracePeriod' : ActorMethod<[string], boolean>,
  'isServiceRestricted' : ActorMethod<[string], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'manuallySetBillingStatus' : ActorMethod<[string, BillingStatus], undefined>,
  'retryPaymentAttempt' : ActorMethod<[string, bigint, bigint], undefined>,
  'saveBusinessFileMetadata' : ActorMethod<[string, FileMetadata], undefined>,
  'saveCallerBusinessProfile' : ActorMethod<[BusinessProfile], undefined>,
  'saveThemePreference' : ActorMethod<[string], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'submitSupportRequest' : ActorMethod<
    [string, string, string, string, SupportCategory, string, bigint],
    undefined
  >,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateSupportRequestStatus' : ActorMethod<
    [string, SupportStatus],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];