/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface PaymentFailureLog {
    attempts: bigint;
    timestamp: bigint;
    amount: bigint;
    lastAttempt: bigint;
    reason: string;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface FileMetadata {
    id: string;
    blob: ExternalBlob;
    name: string;
    ownerBusinessId: string;
    sizeBytes: bigint;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface BillingRecord {
    status: BillingStatus;
    businessId: string;
    paymentFailureLogs: Array<PaymentFailureLog>;
    lastRestrictionTime?: bigint;
    gracePeriodStart?: bigint;
    nextRetryTime?: bigint;
    retryAttempts: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface ShoppingItem {
    productName: string;
    currency: string;
    quantity: bigint;
    priceInCents: bigint;
    productDescription: string;
}
export interface SupportRequest {
    id: string;
    status: SupportStatus;
    organizationName: string;
    fullName: string;
    submittedAt: bigint;
    description: string;
    businessEmail: string;
    supportCategory: SupportCategory;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export type StripeSessionStatus = {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
};
export interface StripeConfiguration {
    allowedCountries: Array<string>;
    secretKey: string;
}
export interface BusinessProfile {
    billingDetails: string;
    size: string;
    subscriptionTier: string;
    businessName: string;
    storageEstimateGb: bigint;
    contactEmail: string;
    industry: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum BillingStatus {
    active = "active",
    grace = "grace",
    restricted = "restricted"
}
export enum SupportCategory {
    technicalIssue = "technicalIssue",
    accountAccess = "accountAccess",
    other = "other",
    security = "security",
    billing = "billing"
}
export enum SupportStatus {
    resolved = "resolved",
    closed = "closed",
    open = "open",
    inProgress = "inProgress"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    checkServiceAccess(businessId: string): Promise<BillingStatus>;
    createCheckoutSession(items: Array<ShoppingItem>, successUrl: string, cancelUrl: string): Promise<string>;
    deleteBusinessProfile(businessId: string): Promise<void>;
    deleteFileMetadata(id: string): Promise<void>;
    deleteSupportRequest(id: string): Promise<void>;
    deleteThemePreference(): Promise<void>;
    getAllBillingRecords(): Promise<Array<BillingRecord>>;
    getAllBusinessProfiles(): Promise<Array<BusinessProfile>>;
    getAllSupportRequests(): Promise<Array<SupportRequest>>;
    getBillingRecordDetails(businessId: string): Promise<BillingRecord | null>;
    getBillingStatus(businessId: string): Promise<BillingStatus>;
    getBusinessFiles(businessId: string): Promise<Array<FileMetadata>>;
    getBusinessProfile(businessId: string): Promise<BusinessProfile | null>;
    getCallerBusinessProfile(): Promise<BusinessProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCustomerBillingStatus(): Promise<BillingStatus>;
    getFileMetadata(id: string): Promise<FileMetadata | null>;
    getStripeSessionStatus(sessionId: string): Promise<StripeSessionStatus>;
    getSupportRequest(id: string): Promise<SupportRequest | null>;
    getThemePreference(): Promise<string | null>;
    handleFailedPayment(businessId: string, reason: string, amount: bigint, timestamp: bigint): Promise<void>;
    handleSuccessfulPayment(businessId: string, amount: bigint, timestamp: bigint): Promise<void>;
    initializeAccessControl(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    isInGracePeriod(businessId: string): Promise<boolean>;
    isServiceRestricted(businessId: string): Promise<boolean>;
    isStripeConfigured(): Promise<boolean>;
    manuallySetBillingStatus(businessId: string, status: BillingStatus): Promise<void>;
    retryPaymentAttempt(businessId: string, attempt: bigint, timestamp: bigint): Promise<void>;
    saveBusinessFileMetadata(businessId: string, file: FileMetadata): Promise<void>;
    saveCallerBusinessProfile(profile: BusinessProfile): Promise<void>;
    saveThemePreference(theme: string): Promise<void>;
    setStripeConfiguration(config: StripeConfiguration): Promise<void>;
    submitSupportRequest(id: string, fullName: string, businessEmail: string, organizationName: string, supportCategory: SupportCategory, description: string, submittedAt: bigint): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateSupportRequestStatus(id: string, status: SupportStatus): Promise<void>;
}
import type { BillingRecord as _BillingRecord, BillingStatus as _BillingStatus, BusinessProfile as _BusinessProfile, ExternalBlob as _ExternalBlob, FileMetadata as _FileMetadata, PaymentFailureLog as _PaymentFailureLog, StripeSessionStatus as _StripeSessionStatus, SupportCategory as _SupportCategory, SupportRequest as _SupportRequest, SupportStatus as _SupportStatus, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this.uploadFile, this.downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this.uploadFile, this.downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this.uploadFile, this.downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this.uploadFile, this.downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this.uploadFile, this.downloadFile, arg1));
            return result;
        }
    }
    async checkServiceAccess(arg0: string): Promise<BillingStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.checkServiceAccess(arg0);
                return from_candid_BillingStatus_n10(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkServiceAccess(arg0);
            return from_candid_BillingStatus_n10(this.uploadFile, this.downloadFile, result);
        }
    }
    async createCheckoutSession(arg0: Array<ShoppingItem>, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async deleteBusinessProfile(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBusinessProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBusinessProfile(arg0);
            return result;
        }
    }
    async deleteFileMetadata(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFileMetadata(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFileMetadata(arg0);
            return result;
        }
    }
    async deleteSupportRequest(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSupportRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSupportRequest(arg0);
            return result;
        }
    }
    async deleteThemePreference(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteThemePreference();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteThemePreference();
            return result;
        }
    }
    async getAllBillingRecords(): Promise<Array<BillingRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBillingRecords();
                return from_candid_vec_n12(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBillingRecords();
            return from_candid_vec_n12(this.uploadFile, this.downloadFile, result);
        }
    }
    async getAllBusinessProfiles(): Promise<Array<BusinessProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBusinessProfiles();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBusinessProfiles();
            return result;
        }
    }
    async getAllSupportRequests(): Promise<Array<SupportRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSupportRequests();
                return from_candid_vec_n15(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSupportRequests();
            return from_candid_vec_n15(this.uploadFile, this.downloadFile, result);
        }
    }
    async getBillingRecordDetails(arg0: string): Promise<BillingRecord | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBillingRecordDetails(arg0);
                return from_candid_opt_n22(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBillingRecordDetails(arg0);
            return from_candid_opt_n22(this.uploadFile, this.downloadFile, result);
        }
    }
    async getBillingStatus(arg0: string): Promise<BillingStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getBillingStatus(arg0);
                return from_candid_BillingStatus_n10(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBillingStatus(arg0);
            return from_candid_BillingStatus_n10(this.uploadFile, this.downloadFile, result);
        }
    }
    async getBusinessFiles(arg0: string): Promise<Array<FileMetadata>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBusinessFiles(arg0);
                return from_candid_vec_n23(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBusinessFiles(arg0);
            return from_candid_vec_n23(this.uploadFile, this.downloadFile, result);
        }
    }
    async getBusinessProfile(arg0: string): Promise<BusinessProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBusinessProfile(arg0);
                return from_candid_opt_n27(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBusinessProfile(arg0);
            return from_candid_opt_n27(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCallerBusinessProfile(): Promise<BusinessProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerBusinessProfile();
                return from_candid_opt_n27(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerBusinessProfile();
            return from_candid_opt_n27(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n28(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n28(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCustomerBillingStatus(): Promise<BillingStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomerBillingStatus();
                return from_candid_BillingStatus_n10(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomerBillingStatus();
            return from_candid_BillingStatus_n10(this.uploadFile, this.downloadFile, result);
        }
    }
    async getFileMetadata(arg0: string): Promise<FileMetadata | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getFileMetadata(arg0);
                return from_candid_opt_n30(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFileMetadata(arg0);
            return from_candid_opt_n30(this.uploadFile, this.downloadFile, result);
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<StripeSessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return from_candid_StripeSessionStatus_n31(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return from_candid_StripeSessionStatus_n31(this.uploadFile, this.downloadFile, result);
        }
    }
    async getSupportRequest(arg0: string): Promise<SupportRequest | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSupportRequest(arg0);
                return from_candid_opt_n35(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSupportRequest(arg0);
            return from_candid_opt_n35(this.uploadFile, this.downloadFile, result);
        }
    }
    async getThemePreference(): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getThemePreference();
                return from_candid_opt_n34(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getThemePreference();
            return from_candid_opt_n34(this.uploadFile, this.downloadFile, result);
        }
    }
    async handleFailedPayment(arg0: string, arg1: string, arg2: bigint, arg3: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.handleFailedPayment(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.handleFailedPayment(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async handleSuccessfulPayment(arg0: string, arg1: bigint, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.handleSuccessfulPayment(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.handleSuccessfulPayment(arg0, arg1, arg2);
            return result;
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isInGracePeriod(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isInGracePeriod(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isInGracePeriod(arg0);
            return result;
        }
    }
    async isServiceRestricted(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isServiceRestricted(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isServiceRestricted(arg0);
            return result;
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async manuallySetBillingStatus(arg0: string, arg1: BillingStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.manuallySetBillingStatus(arg0, to_candid_BillingStatus_n36(this.uploadFile, this.downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.manuallySetBillingStatus(arg0, to_candid_BillingStatus_n36(this.uploadFile, this.downloadFile, arg1));
            return result;
        }
    }
    async retryPaymentAttempt(arg0: string, arg1: bigint, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.retryPaymentAttempt(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.retryPaymentAttempt(arg0, arg1, arg2);
            return result;
        }
    }
    async saveBusinessFileMetadata(arg0: string, arg1: FileMetadata): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveBusinessFileMetadata(arg0, await to_candid_FileMetadata_n38(this.uploadFile, this.downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveBusinessFileMetadata(arg0, await to_candid_FileMetadata_n38(this.uploadFile, this.downloadFile, arg1));
            return result;
        }
    }
    async saveCallerBusinessProfile(arg0: BusinessProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerBusinessProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerBusinessProfile(arg0);
            return result;
        }
    }
    async saveThemePreference(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveThemePreference(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveThemePreference(arg0);
            return result;
        }
    }
    async setStripeConfiguration(arg0: StripeConfiguration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0);
            return result;
        }
    }
    async submitSupportRequest(arg0: string, arg1: string, arg2: string, arg3: string, arg4: SupportCategory, arg5: string, arg6: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitSupportRequest(arg0, arg1, arg2, arg3, to_candid_SupportCategory_n41(this.uploadFile, this.downloadFile, arg4), arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitSupportRequest(arg0, arg1, arg2, arg3, to_candid_SupportCategory_n41(this.uploadFile, this.downloadFile, arg4), arg5, arg6);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateSupportRequestStatus(arg0: string, arg1: SupportStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSupportRequestStatus(arg0, to_candid_SupportStatus_n43(this.uploadFile, this.downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSupportRequestStatus(arg0, to_candid_SupportStatus_n43(this.uploadFile, this.downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_BillingRecord_n13(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BillingRecord): BillingRecord {
    return from_candid_record_n14(uploadFile, downloadFile, value);
}
function from_candid_BillingStatus_n10(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BillingStatus): BillingStatus {
    return from_candid_variant_n11(uploadFile, downloadFile, value);
}
async function from_candid_ExternalBlob_n26(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await downloadFile(value);
}
async function from_candid_FileMetadata_n24(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FileMetadata): Promise<FileMetadata> {
    return await from_candid_record_n25(uploadFile, downloadFile, value);
}
function from_candid_StripeSessionStatus_n31(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeSessionStatus): StripeSessionStatus {
    return from_candid_variant_n32(uploadFile, downloadFile, value);
}
function from_candid_SupportCategory_n20(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SupportCategory): SupportCategory {
    return from_candid_variant_n21(uploadFile, downloadFile, value);
}
function from_candid_SupportRequest_n16(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SupportRequest): SupportRequest {
    return from_candid_record_n17(uploadFile, downloadFile, value);
}
function from_candid_SupportStatus_n18(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SupportStatus): SupportStatus {
    return from_candid_variant_n19(uploadFile, downloadFile, value);
}
function from_candid_UserRole_n28(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n29(uploadFile, downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(uploadFile, downloadFile, value);
}
function from_candid_opt_n22(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BillingRecord]): BillingRecord | null {
    return value.length === 0 ? null : from_candid_BillingRecord_n13(uploadFile, downloadFile, value[0]);
}
function from_candid_opt_n27(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BusinessProfile]): BusinessProfile | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n30(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FileMetadata]): Promise<FileMetadata | null> {
    return value.length === 0 ? null : await from_candid_FileMetadata_n24(uploadFile, downloadFile, value[0]);
}
function from_candid_opt_n34(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n35(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SupportRequest]): SupportRequest | null {
    return value.length === 0 ? null : from_candid_SupportRequest_n16(uploadFile, downloadFile, value[0]);
}
function from_candid_opt_n6(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _BillingStatus;
    businessId: string;
    paymentFailureLogs: Array<_PaymentFailureLog>;
    lastRestrictionTime: [] | [bigint];
    gracePeriodStart: [] | [bigint];
    nextRetryTime: [] | [bigint];
    retryAttempts: bigint;
}): {
    status: BillingStatus;
    businessId: string;
    paymentFailureLogs: Array<PaymentFailureLog>;
    lastRestrictionTime?: bigint;
    gracePeriodStart?: bigint;
    nextRetryTime?: bigint;
    retryAttempts: bigint;
} {
    return {
        status: from_candid_BillingStatus_n10(uploadFile, downloadFile, value.status),
        businessId: value.businessId,
        paymentFailureLogs: value.paymentFailureLogs,
        lastRestrictionTime: record_opt_to_undefined(from_candid_opt_n7(uploadFile, downloadFile, value.lastRestrictionTime)),
        gracePeriodStart: record_opt_to_undefined(from_candid_opt_n7(uploadFile, downloadFile, value.gracePeriodStart)),
        nextRetryTime: record_opt_to_undefined(from_candid_opt_n7(uploadFile, downloadFile, value.nextRetryTime)),
        retryAttempts: value.retryAttempts
    };
}
function from_candid_record_n17(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _SupportStatus;
    organizationName: string;
    fullName: string;
    submittedAt: bigint;
    description: string;
    businessEmail: string;
    supportCategory: _SupportCategory;
}): {
    id: string;
    status: SupportStatus;
    organizationName: string;
    fullName: string;
    submittedAt: bigint;
    description: string;
    businessEmail: string;
    supportCategory: SupportCategory;
} {
    return {
        id: value.id,
        status: from_candid_SupportStatus_n18(uploadFile, downloadFile, value.status),
        organizationName: value.organizationName,
        fullName: value.fullName,
        submittedAt: value.submittedAt,
        description: value.description,
        businessEmail: value.businessEmail,
        supportCategory: from_candid_SupportCategory_n20(uploadFile, downloadFile, value.supportCategory)
    };
}
async function from_candid_record_n25(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    blob: _ExternalBlob;
    name: string;
    ownerBusinessId: string;
    sizeBytes: bigint;
}): Promise<{
    id: string;
    blob: ExternalBlob;
    name: string;
    ownerBusinessId: string;
    sizeBytes: bigint;
}> {
    return {
        id: value.id,
        blob: await from_candid_ExternalBlob_n26(uploadFile, downloadFile, value.blob),
        name: value.name,
        ownerBusinessId: value.ownerBusinessId,
        sizeBytes: value.sizeBytes
    };
}
function from_candid_record_n33(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
    response: string;
}): {
    userPrincipal?: string;
    response: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n34(uploadFile, downloadFile, value.userPrincipal)),
        response: value.response
    };
}
function from_candid_record_n5(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(uploadFile, downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(uploadFile, downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n11(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    grace: null;
} | {
    restricted: null;
}): BillingStatus {
    return "active" in value ? BillingStatus.active : "grace" in value ? BillingStatus.grace : "restricted" in value ? BillingStatus.restricted : value;
}
function from_candid_variant_n19(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    resolved: null;
} | {
    closed: null;
} | {
    open: null;
} | {
    inProgress: null;
}): SupportStatus {
    return "resolved" in value ? SupportStatus.resolved : "closed" in value ? SupportStatus.closed : "open" in value ? SupportStatus.open : "inProgress" in value ? SupportStatus.inProgress : value;
}
function from_candid_variant_n21(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    technicalIssue: null;
} | {
    accountAccess: null;
} | {
    other: null;
} | {
    security: null;
} | {
    billing: null;
}): SupportCategory {
    return "technicalIssue" in value ? SupportCategory.technicalIssue : "accountAccess" in value ? SupportCategory.accountAccess : "other" in value ? SupportCategory.other : "security" in value ? SupportCategory.security : "billing" in value ? SupportCategory.billing : value;
}
function from_candid_variant_n29(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n32(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: from_candid_record_n33(uploadFile, downloadFile, value.completed)
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
function from_candid_vec_n12(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BillingRecord>): Array<BillingRecord> {
    return value.map((x)=>from_candid_BillingRecord_n13(uploadFile, downloadFile, x));
}
function from_candid_vec_n15(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SupportRequest>): Array<SupportRequest> {
    return value.map((x)=>from_candid_SupportRequest_n16(uploadFile, downloadFile, x));
}
async function from_candid_vec_n23(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FileMetadata>): Promise<Array<FileMetadata>> {
    return await Promise.all(value.map(async (x)=>await from_candid_FileMetadata_n24(uploadFile, downloadFile, x)));
}
function to_candid_BillingStatus_n36(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BillingStatus): _BillingStatus {
    return to_candid_variant_n37(uploadFile, downloadFile, value);
}
async function to_candid_ExternalBlob_n40(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await uploadFile(value);
}
async function to_candid_FileMetadata_n38(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FileMetadata): Promise<_FileMetadata> {
    return await to_candid_record_n39(uploadFile, downloadFile, value);
}
function to_candid_SupportCategory_n41(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SupportCategory): _SupportCategory {
    return to_candid_variant_n42(uploadFile, downloadFile, value);
}
function to_candid_SupportStatus_n43(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SupportStatus): _SupportStatus {
    return to_candid_variant_n44(uploadFile, downloadFile, value);
}
function to_candid_UserRole_n8(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(uploadFile, downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(uploadFile, downloadFile, value);
}
function to_candid_opt_n1(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(uploadFile, downloadFile, value));
}
function to_candid_record_n3(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n39(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    blob: ExternalBlob;
    name: string;
    ownerBusinessId: string;
    sizeBytes: bigint;
}): Promise<{
    id: string;
    blob: _ExternalBlob;
    name: string;
    ownerBusinessId: string;
    sizeBytes: bigint;
}> {
    return {
        id: value.id,
        blob: await to_candid_ExternalBlob_n40(uploadFile, downloadFile, value.blob),
        name: value.name,
        ownerBusinessId: value.ownerBusinessId,
        sizeBytes: value.sizeBytes
    };
}
function to_candid_variant_n37(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BillingStatus): {
    active: null;
} | {
    grace: null;
} | {
    restricted: null;
} {
    return value == BillingStatus.active ? {
        active: null
    } : value == BillingStatus.grace ? {
        grace: null
    } : value == BillingStatus.restricted ? {
        restricted: null
    } : value;
}
function to_candid_variant_n42(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SupportCategory): {
    technicalIssue: null;
} | {
    accountAccess: null;
} | {
    other: null;
} | {
    security: null;
} | {
    billing: null;
} {
    return value == SupportCategory.technicalIssue ? {
        technicalIssue: null
    } : value == SupportCategory.accountAccess ? {
        accountAccess: null
    } : value == SupportCategory.other ? {
        other: null
    } : value == SupportCategory.security ? {
        security: null
    } : value == SupportCategory.billing ? {
        billing: null
    } : value;
}
function to_candid_variant_n44(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SupportStatus): {
    resolved: null;
} | {
    closed: null;
} | {
    open: null;
} | {
    inProgress: null;
} {
    return value == SupportStatus.resolved ? {
        resolved: null
    } : value == SupportStatus.closed ? {
        closed: null
    } : value == SupportStatus.open ? {
        open: null
    } : value == SupportStatus.inProgress ? {
        inProgress: null
    } : value;
}
function to_candid_variant_n9(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, uploadFile, downloadFile, options.processError);
}
